services:
  bookbag:
    image: codeberg.org/bookbag/bookbag:latest
    container_name: bookbag
    ports:
      - "8084:8084"
    volumes:
      - PATH/FOR/YOUR/LIBRARY/FOLDER:/books
      - PATH/FOR/YOUR/CONFIG/FOLDER:/config
    restart: unless-stopped